### ISSUE TITLE
Broken examples and benchmarks after monorepo refactor

### ISSUE THREAD

**Issue by codyzu** [oramasearch/orama#117]
**Describe the bug**
Commit d0f95d789ed80de2f8ebc31eedee5e72c0a27877 broke the react example (`App.tsx` was deleted) and deleted the benchmarks. Was this intentional? Do you want a PR to clean this up or add them back?

**Comment by micheleriva** [comment]
Hey @codyzu,
I am thinking of removing the examples actually. We already removed the benchmarks (will make a separate repo) for them

**Comment by mrbrianevans** [comment]
Are there any benchmarks currently available? 

Maybe this should be a separate issue but it would be nice to have some common usecase benchmarks run on every PR with a github action to show the performance implications of any changes (whether good or bad) compared to current master branch.

Would also be nice to have in the readme or docs to show any prospective users what performance can be expected in a few different scenarios (even just a rough ballpark figure).
