### ISSUE TITLE
Add support for tamil language unicode texts and others fonts support

### ISSUE THREAD

**Issue by gitexp2050** [oramasearch/orama#162]
Add support for tamil language unicode texts and others fonts support

**Comment by haruncurak** [comment]
Almost done adding Tamil language + font support, just need to find a way to generate a .js version of the Tamil stemmer from Snowball

**Comment by haruncurak** [comment]
@micheleriva do you remember what you used to generate the (languagename).js files in stemmers/lib ?

**Comment by micheleriva** [comment]
Hi @haruncurak, we used Snowball: https://snowball.tartarus.org/
