### ISSUE TITLE
Add support for highlighting and context

### ISSUE THREAD

**Issue by Ceres6** [oramasearch/orama#200]
**Is your feature request related to a problem? Please describe.**
In some context when you are showing results of a query, especially for large documents, it would be useful to have the context where the matching occurred inside the document, to help the user to choose between different results.

**Describe the solution you'd like**
It should be possible to specify a context length and get an array with data on where matches occurred and tokens/word around that. 

My Idea would be to add a field to results like
```typescript
{
  context: {
    match: string
    position: {
      start: number
      end: number
    }
  }
}
```

**Describe alternatives you've considered**
Really any way to get similar info with different format, maybe a snippet.

**Additional context**

**Comment by micheleriva** [comment]
As discussed separately, this will start as a plugin. Thanks Carlos!

**Comment by n4bb12** [comment]
It would be great if this highlights could be returned in a property that already contains `<mark>` wrappers, so folks don't need to implement this themselves. See for [Algolia's output](https://www.algolia.com/doc/api-reference/api-methods/search/#json-format) for comparison.
