### ISSUE TITLE
[Astro] Use a Lyra database globally and pass it throught components.

### ISSUE THREAD

**Issue by browser-bug** [oramasearch/orama#249]
**Describe the bug**
I'm trying to integrate Lyra inside an Astro project to use a global database built at build time. Despite the feasibility of the task, I did some tests beforehand, trying to build inside the Astro formatter a simple db and pass it to a React component.
```typescript
---
import { create, insertBatch } from "@lyrasearch/lyra";

const newsDB = await create({
  schema: {
    title: "string",
    author: "string",
    description: "string",
  },
  defaultLanguage: "italian",
});
await insertBatch(newsDB, [
  {
    title: "foo",
    author: "foo",
    description: "foo",
  },
]);
---
<PostList posts={langPosts} db={newsDB} client:load />
```
Then inside `PostList`:
```typescript
import { search } from "@lyrasearch/lyra";

export const PostList = ({ db }) => {
  console.log(db); // missing the `components` functions inside the db object
  console.log(search(db, {term: "test"}); // crashes with error

  ...
}
```

For some reason during the props injection the `newsDB` loses some properties, for instance this is the components Object logged inside `PostList`:
```
"components": {
    "tokenizer": {
      "enableStopWords": true,
      "enableStemming": true,
      "stemmingFn": null,
      "customStopWords": [],
      "tokenizerFn": null,
      "assertSupportedLanguage": null
    },
    "algorithms": {
      "intersectTokenScores": null
    }
  }
```

As you can see the tokenizerFn and more is null for some reason and hence I get this error while searching a term:
```
Uncaught (in promise) TypeError: lyra.components.tokenizer.tokenizerFn is not a function
```

This can be related to Astro since it is passing a constant object with JS functions inside it (e.g. stemming, tokenizer) from the frontmatter to the html section, but I'm asking anyway just in case.

**Expected behavior**
The database is correctly built once and usable across components.

**Comment by micheleriva** [comment]
This might be due to the fact that it is not possible to serialize functions, so whenever you create a new database via the `plugin-data-persistence` plugin, you're missing the tokenizer.

cc @castarco, we need to update the `plugin-data-persistence` plugin and then update the Astro plugin as well :)

**Comment by browser-bug** [comment]
> This might be due to the fact that it is not possible to serialize functions, so whenever you create a new database via the `plugin-data-persistence` plugin, you're missing the tokenizer.
> 
> cc @castarco, we need to update the `plugin-data-persistence` plugin and then update the Astro plugin as well :)

I'm not using the `plugin-data-persistence` tho. Just the standard Lyra library. Or is this related to something used by it under the hood?

**Comment by micheleriva** [comment]
That's really strange then. Could you please give us a reproduction repo?

**Comment by browser-bug** [comment]
> Hi to all, I think this is closely related to Astro and [Dynamic Attributes](https://docs.astro.build/en/core-concepts/astro-components/#dynamic-attributes).
> 
> ```
> HTML attributes will be converted to strings, so it is not possible to pass functions and objects to HTML elements.
> ```

Yes I think this is the matter of the issue. In this case I have to think about another way to generate the database at build time and access it from inside each component. If you have any ideas your welcomed to suggest :D

**Comment by castarco** [comment]
Sorry, I was not very active for a while. I'll check during this week!
