### ISSUE TITLE
Is Lyra deployable on Vercel?

### ISSUE THREAD

**Issue by gtoshinakano** [oramasearch/orama#250]
Hi, I am very interested in using Lyra for a search feature in my web application built in Next JS and deployed on Vercel.

I would like to know if is it deployable on Vercel Edge functions or API endpoints.

Do you recommend Lyra in this case? And another question, does it work well with PrismaORM? My idea is to fetch the data using Prisma, inserting them on Lyra to make it easily searchable, what do you guys think?

**Comment by micheleriva** [comment]
Hi!
Yes, Lyra works on Vercel. We're gonna release some documentation soon.
