### ISSUE TITLE
Internals did not make into 'index.d.ts'

### ISSUE THREAD

**Issue by bogacg** [oramasearch/orama#273]
Somehow Internals has no member in `index.d.ts`. Can't use `tokenize` (or other functions of internals like `boundedLevenshtein`) with Typescript & Vite.

If I try something like this: `import { tokenize } from '@lyrasearch/lyra/dist/internals'` while VS-Code is happy this time I get error building the app:

```
[commonjs--resolver] Missing "./dist/tokenizer" specifier in "@lyrasearch/lyra" package
{
  code: 'PLUGIN_ERROR',
  plugin: 'commonjs--resolver',
  hook: 'resolveId',
```

**Comment by micheleriva** [comment]
@ShogunPanda would you mind taking a look at this?

**Comment by bogacg** [comment]
@micheleriva yes, `^0.4.5`

**Comment by ShogunPanda** [comment]
@bogacg Internals are purposely not in `@lyrasearch/lyra` export.

You can import them by importing from `@lyrasearch/lyra/internals`, as defined in `exports` in Lyra's `package.json`.
Can you please try that and tell me if works?

**Comment by bogacg** [comment]
@ShogunPanda doing so did result with a successful build but in VS Code I'm getting error:

> Cannot find module '@lyrasearch/lyra/internals' or its corresponding type declarations. ts(2307)

Though that TS file is inside a workspace environment. Maybe a parent `tsconfig` is preventing VS Code to  correctly resolve.

Side note: Testing tokenize function I see that some Turkish letters did not cleared from accent/diacritics: `ĞğşŞ`

**Comment by ShogunPanda** [comment]
Happy to know the main issue solved.

Did restarting VSCode helped?
Otherwise, if you can provide a repro repo I'll back to debug the issue.

About the problem with the Turkish language, would you like to send a PR to fix it?

**Comment by bogacg** [comment]
Ok lets see what I can do.

**Comment by david10sing** [comment]
@bogacg 

If you need a workaround, could you try the following:

Create a `declaration.d.ts` on root of your project

```ts
declare module '@lyrasearch/plugin-astro/internals' {
  export * from '@lyrasearch/plugin-astro/dist/internals'
}
```
