### ISSUE TITLE
200k documents search leads to maximum call stack exceeded

### ISSUE THREAD

**Issue by user472** [oramasearch/orama#301]
**Describe the bug**
When searching with Lyra for 200k documents in it it throws the error `Maximum call stack exceeded`. This is error is thrown exactly starting from 100,188 documents matching the search query.

**To Reproduce**

Execute the code below.

```
import { create, insertBatch, search } from '@lyrasearch/lyra';

async function main() {
  const db = await create({
    schema: {
      title: 'string',
    },
  });

  // the search works exactly until a document count of 100187
  const data = Array.from({ length: 200_000 }).map(() => ({ title: 'tttt' }));

  await insertBatch(db, data);

  const res = await search(db, {
    term: 'tttt',
    properties: ['title'],
  });

  console.log('hits count', res.hits.length);
}

main();

```

**Expected behavior**
Search result should be returned by lyra without throwing an error.

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.2.1
 - ts-node version 10.9.1 and tauri version 1.2.3

**Comment by micheleriva** [comment]
Hey there,
there might be many reasons why you're running out of call stack space.

1) We have a PR open that avoids many recursive calls, which may lead to this error specifically from time to time (https://github.com/LyraSearch/lyra/pull/305)
2) It also depends on your dataset size and available RAM; Lyra is in-memory, so needs to load everything in-memory to operate

**Comment by micheleriva** [comment]
@user472 on what machine are you running Orama? How much RAM do you allocate to the process? Are you in a container?

I tested locally with 1M docs on a MacBook Pro M1 Pro (16GB RAM) and I had no problems at all, it might depend on the environment. 200k strings are not that much, unless they're like billions of characters each

**Comment by user472** [comment]
@micheleriva I am on a MacBook Pro M1 Max (32 GB RAM) and also running it locally without any restrictions on how much RAM it is allowed to use. The string that I store for each document is still `tttt` so this should also not be an issue.

Which version of node are you running?
