### ISSUE TITLE
unpkg link from Docs does not work

### ISSUE THREAD

**Issue by leeoniya** [oramasearch/orama#325]
https://docs.oramasearch.com/#installation

https://unpkg.com/@oramasearch/orama@latest/dist/index.js

this also does not work:

https://unpkg.com/@orama/orama

**Comment by mateonunez** [comment]
> https://unpkg.com/@oramasearch/orama@latest/dist/index.js

There's a typo in the documentation, the correct name is @orama and not @oramasearch. I think you can send a PR for that.

> 
> this also does not work:
> 
> https://unpkg.com/@orama/orama

It's working at the following link: https://unpkg.com/@orama/orama@1.0.0-beta.4/dist/index.js

It's only missing che correct path of the index.js! 😉

**Comment by kamilogorek** [comment]
Looks like it's fixed now and can be closed.

**Comment by micheleriva** [comment]
Fixed, closing
