### ISSUE TITLE
search function doesn't return item that exists in the db

### ISSUE THREAD

**Issue by skoropadas** [oramasearch/orama#327]
**Describe the bug**
I have a db that contains an object with a field `section` that has the value "NgDocEntity". I am trying to find it using the `search` function, but Lyra/Orama returns anything except this object. However, if I add only this record or just a few, the search returns the correct result. I have tried different search settings and database configurations, but nothing has helped.

**To Reproduce**
Here is a [codesandbox](https://codesandbox.io/s/lyrasearch-3k4rkd?file=/src/index.ts) example

**Expected behavior**
Should return this record

**Desktop (please complete the following information):**
 - OS: All
 - Browser All

**Additional context**
Nope

**Comment by micheleriva** [comment]
Fixed in `v1.0.0-beta.7`, you can update from npm

**Comment by skoropadas** [comment]
@micheleriva works perfect! big thanks!
