### ISSUE TITLE
Unable to use a complex property in schema

### ISSUE THREAD

**Issue by karansapolia** [oramasearch/orama#333]
**Describe the bug**
I want to declare a schema of this shape:
```
schema: {
      title: 'string',
      content: 'string',
      url: 'string',
      breadCrumbs: [
        {
          label: 'string',
          disabled: 'boolean',
        },
      ],
    },
```
But am unable to do so. We cannot have a property in the schema that is an array of objects?

**To Reproduce**
1. Create a new oramasearch db and create the schema
2. Add a property to the schema that is an array of objects

**Expected behavior**
I should be able to specify a property as an array of object like we can in TS

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 13.2.1
 - Browser: All
 - LyraSearch Version: 0.4.11

**Error shown**
```
  Property 'breadCrumbs' is incompatible with index signature.
    Type '[{ label: "string"; disabled: "boolean"; }]' is not assignable to type 'PropertiesSchema | PropertyType'.
      Type '[{ label: "string"; disabled: "boolean"; }]' is not assignable to type 'PropertiesSchema'.
        Index signature for type 'string' is missing in type '[{ label: "string"; disabled: "boolean"; }]'.ts(2344)
```

**Comment by micheleriva** [comment]
Hi, you're correct, arrays are not currently supported, and we don't have plans to support them in the near future... I suggest you fallback to plain JS objects or joined strings for this task
