### ISSUE TITLE
Metrics aggregations

### ISSUE THREAD

**Issue by or2e** [oramasearch/orama#335]
Hi. Thank you very much for your work
I couldn't find a related topic, so here's the issue.

**Task**: get min/max values for [Number facet](https://docs.oramasearch.com/usage/search/facets#number-facets)

<details>
<summary>UI example</summary>

<img width="234" alt="image" src="https://user-images.githubusercontent.com/33551334/229249476-6d973c44-29f2-424c-a99b-b437f4365ec4.png">
</details>

For example, in ElasticSearch for a similar task there's [metrics aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-max-aggregation.html)

<details>
<summary>Trying to solve a problem "head-on"</summary>

```TS
import { create, search, insertMultiple, stemmers } from '@orama/orama';


const stats: Record<string, { min: number; max: number }> = {
  price: {
    min: 0,
    max: 0,
  },
};

const db = await create({
  schema: {
    name: 'string',
    foo: 'string',
    price: 'number',
  },
  components: {
    tokenizer: {
      language: 'english',
      stemmer: stemmers.english,
    },
    afterInsert: (_orama, _id, doc) => {
      for (const key in doc) {
        if (key in stats) {
          if (stats[key].min === 0) {
            stats[key].min = doc[key] as number;
          }

          stats[key].min = Math.min(stats[key].min, doc[key] as number);
          stats[key].max = Math.max(stats[key].max, doc[key] as number);
        }
      }
    },
  },
});

await Promise.all([loadItems(), userStore.fetchUserItems()]);

const docs = [
  {
    name: 'The prestige',
    foo: 'bar',
    price: 500,
    tags: ['tag1', 'tag2'],
  },
  {
    name: 'Big Fish',
    foo: 'bar',
    price: 1000,
    tags: ['tag1'],
  },
];

await insertMultiple(db, docs, 1200);

const results = await search(db, {
  term: 'bar',
  properties: ['foo'],
  facets: {
    name: {
      sort: 'DESC',
    },
    tags: {
      sort: 'DESC',
    },
    price: {
      ranges: [
        {
          from: stats.price.min,
          to: stats.price.max,
        },
      ],
    },
  },
});
```
<img width="363" alt="image" src="https://user-images.githubusercontent.com/33551334/229249087-3e34ddb3-1ee7-48ae-bc80-471d6a8c4b0a.png">
</details>

**Comment by micheleriva** [comment]
@ShogunPanda maybe we can solve this with hooks?

**Comment by ShogunPanda** [comment]
Yes, I suggest to track this in insertion time. Any component which receives a document (`beforeInsert`, `afterInsert` and similar) will make the trick.

Closing this as it is not planned. If you see the benefit of having it inside Orama core let us know and I'll reopen.
