### ISSUE TITLE
Using NestJS, I'm getting this error: const batch = docs.slice(i * batchSize!, (i + 1) * batchSize!)

### ISSUE THREAD

**Issue by ericsison-dev** [oramasearch/orama#336]
**Describe the bug**
I'm using NestJS to hopefully host a FTS using oramasearch. I am able to create the database, but throws me an error when trying to insert multiple documents into it.

**To Reproduce**
1. I created a simple JSON file to mock an array of persons
2. Created a service to `create` the database and `insertMultiple` person data into it.

           
           import * as persons from '/mock/persons.json';

            @Injectable()
            export class AppService {
                 async initializeDb() {
                   const db = await create({
                         schema: {
                             firstName: 'string',
                             middleName: 'string',
                             lastName: 'string',
                             address: 'string',
                             country: 'string',
                         },
                    });
                    await insertMultiple(db, persons, 200) 
                }     
            }
 
4. Added a controller to create a route for it. In this case, just a simple `GET` request: `/api/fts`
5. Then calling the end point (through my browser, since I'm only using `GET` request) terminates my server (note: I also tried putting it into a try-catch block), throws me the error in my console, and gives me a warning in my browser: `crbug/1173575, non-JS module files deprecated.`
6. See error

**Expected behavior**
I just followed the usage guide from the docs. Also, I noticed that the docs says, when inserting multiple documents into the database: `await insertMultiple(movieDB, docs, { batchSize: 500 });` - the 3rd parameter being an object. However, with the current version that I'm working on right now, `batchSize?: number` is the 3rd parameter.

**Screenshots**
![Screenshot from 2023-04-02 04-39-15](https://user-images.githubusercontent.com/65406753/229313397-4d79c5df-aaab-432f-93d0-9ab3cc846d0a.png)
![Screenshot from 2023-04-02 04-39-41](https://user-images.githubusercontent.com/65406753/229313404-a6507a13-4852-493e-8f6b-603a471987bd.png)

**Desktop:**
 - OS: Linux Ubuntu 22
 - Browser: Google Chrome Version 110.0.5481.100 (Official Build) (64-bit)
 - Oramasearch Version: ^1.0.0-beta.7

**Comment by micheleriva** [comment]
Hi there, is it possible to have a reproduction via codesandbox or replit?

**Comment by nxf-gerdjungbluth** [comment]
@ericsison-dev From the code you presented I can only asume that you assign `db` as a `const` within the `initializeDb()` method. By definition it can not be accessed from any NestJS controller.
