### ISSUE TITLE
Inconsistent results with longer words

### ISSUE THREAD

**Issue by james2doyle** [oramasearch/orama#340]
**Describe the bug**
I am using Orama to index some pages in a static Next site. I am using an API "page". Basically just a simple request handler that takes the `term` as a query string and passes it to `await search({ term: req.query.term })`.

What I have noticed is that there are some inconsistent results in the search when it comes to longer words. At a certain point, it stops matching partial words and will only match exact ones.

**To Reproduce**
* Create an Orama DB with the default config
* Load it with entries that have long words
* Search for partial matches on terms

**Expected behavior**
Matching words should return matching results

**Screenshots**

I took a video showing the issue.

https://user-images.githubusercontent.com/1425304/230482493-ead7de3d-a8ed-4eb5-af06-97c311790492.mp4

**Additional context**

* Node v16.15.0
* @orama/orama v1.0.0-beta.8
* @orama/plugin-data-persistence v1.0.0-beta.8 (using "dpack")

**Comment by micheleriva** [comment]
Hi @james2doyle, I believe this is due to stemming. Can you please try the following?

```js
import { create } from '@orama/orama' 

await create({
  schema: { ... },
  components: {
    tokenizer: {
      stemming: false
    }
  }
})
```

I think we should enhance our documentation by writing this down explicitly.

Can you please try this and let us know if it solves the issue?

**Comment by james2doyle** [comment]
@micheleriva Yep that solved it!

Thanks for the help
