### ISSUE TITLE
Orama is not compatible with Node v14

### ISSUE THREAD

**Issue by mateonunez** [oramasearch/orama#341]
**Describe the bug**
Orama is not compatible with Node v14 since the codebase uses the `hasOwn` method.

**Expected behavior**
Orama should be compatible with Node v14 or older versions since the `utils.ts` makes a check on that method.

**Screenshots**
![image](https://user-images.githubusercontent.com/11861080/230721104-5603d79b-1475-415b-b61c-e59266af021e.png)

**Comment by micheleriva** [comment]
I thought we had already solved this! Can you open a PR? 🙏
