### ISSUE TITLE
Docs Batch Insertion and batchSize usage

### ISSUE THREAD

**Issue by llooz** [oramasearch/orama#345]
On the [docs](https://github.com/oramasearch/orama/blob/main/packages/docs/pages/usage/insert.mdx#batch-insertion) there is an example of `insertMultiple` with `batchSize`  specified via an object while it should be passed as a third parameter.

I caught it because I wanted to try out the library and I did just a copy / paste but it wasn't working 😅

**Comment by micheleriva** [comment]
Hi @llooz! Thanks for noticing this. Would you mind opening a PR for fixing the docs?
