### ISSUE TITLE
Multivalue doc fields

### ISSUE THREAD

**Issue by SergeyRe** [oramasearch/orama#359]
dont see possibility to correctly indexing and  faceting multivalue fields 
something like actors : ["Clint Eastwood ","Tom Hanks"]
facets values and their counts have to be represented for each actors/fields values  separately

**Comment by micheleriva** [comment]
That's correct, we don't currently support arrays as data type in the schema definition. You could join the array into a single string, but you would lose granular filters and faceting, so I get your problem.

We don't have this feature planned, but maybe we can have a chat about it. @ShogunPanda wdyt?
