### ISSUE TITLE
Docusaurus Plugin tests are breaking

### ISSUE THREAD

**Issue by micheleriva** [oramasearch/orama#360]
**Describe the bug**
Tests are breaking with the current version of Orama and the official Docusaurus plugin

**To Reproduce**
1. Go to `packages/plugin-docusaurus`
2. Enable tests (rename `-test` script into `test`)
3. Run `pnpm t`

cc. @simoneb

**Comment by kamilogorek** [comment]
Everything passes on master branch with Node v20 👀 

```
> @orama/plugin-docusaurus@1.0.0-beta.16 test ~/orama/packages/plugin-docusaurus
> node --loader=tsx --no-warnings=loader --test ./test/integration.ts | tap-mocha-reporter spec


plugin is able to generate orama DB at build time
  ✓ plugin is able to generate orama DB at build time
  ✓ generated DBs have indexed pages content

  2 passing (44s)
```

**Comment by guilhermelimak** [comment]
Yep, same here, running fine on node v20 and v18

**Comment by micheleriva** [comment]
It looks like now it's working on CI too. Closing this
