### ISSUE TITLE
Plugin Astro fail to build on Windows

### ISSUE THREAD

**Issue by TheZal** [oramasearch/orama#367]
**Describe the bug**
When the build command is executed on Windows the build fail due to an error on the destination path of the assets folder.

**To Reproduce**
1. Create a new Astro project
2. Install @orama/plugin-astro
3. Setup the plugin
4. Run astro build

**Expected behavior**
The build to complete and to create the database asset on the folder inside the project

**Screenshots**
![image](https://user-images.githubusercontent.com/12339188/236629958-c442230e-f5e2-447c-81b0-c8dce8c31a7e.png)

**Desktop**
 - OS: Windows 10
 
**Additional context**
The problem is created by the path that is not right escaped for a Windows system.
I can fix it with a PR if you let me :)

**Comment by micheleriva** [comment]
cc. @castarco, @simoneb

**Comment by micheleriva** [comment]
@TheZal can you try it with `orama v1.0.0-beta.16`?

**Comment by TheZalRevolt** [comment]
Gonna try asap!

**Comment by TheZal** [comment]
Gonna try ASAP! :)

**Comment by TheZal** [comment]
It seems that the issue remains...
![image](https://github.com/oramasearch/orama/assets/12339188/fd767b85-1b2b-458b-b1cf-a47d31e6ba81)
![image](https://github.com/oramasearch/orama/assets/12339188/eb085236-af70-4b3f-a2b4-436560a2bde2)

**Comment by Balastrong** [comment]
If my Windows computer will assist me... otherwise I'll pair with @TheZal one day this week :)

**Comment by micheleriva** [comment]
Awesome, thank you @Balastrong! Write me in the Orama Slack channel, I got something for you to thank you for the contribs 🙂

**Comment by TheZal** [comment]
Absolutely happy to pair!

**Comment by micheleriva** [comment]
Thank you folks 🙏
