### ISSUE TITLE
docs: link on plugins page redirects incorrectly

### ISSUE THREAD

**Issue by AviAvinav** [oramasearch/orama#370]
**Describe the bug**
In the docs, https://docs.oramasearch.com/plugins, in the last line the link to the packages on the github repo is wrong.

**Expected behavior**
It should redirect to https://github.com/oramasearch/orama/tree/main/packages instead of https://github.com/oramasearch/orama/packages (this link leads to the page shown below)

**Screenshots**
<img src="https://i.ibb.co/cTDmsP7/Screenshot-2023-05-08-165607.png" />

**Comment by micheleriva** [comment]
Hi! Thanks for spotting this. It should link to [https://github.com/oramasearch/orama/tree/main/packages](https://github.com/oramasearch/orama/tree/main/packages).

Would you be up for opening a PR for fixing this?

**Comment by AviAvinav** [comment]
Yeah, I would like to work on this and open a PR
