### ISSUE TITLE
The 'remove' API does not remove a document properly

### ISSUE THREAD

**Issue by ezzaouia** [oramasearch/orama#386]
The 'remove' API does not remove a document properly

**To Reproduce**
1. Insert a document with id say '123'
2. Remove the document with id '123'
3. Insert a new document with id '123' -> Error ; A document with id "123" already exists

The steps outlined above are meant to perform an update of an existing document.

[Codesandbox](https://codesandbox.io/s/xenodochial-murdock-m83bhs?file=/src/index.js)

**Expected behavior**
When removing a document, the document should be removed completely.

**Comment by micheleriva** [comment]
@allevo I think this is a problem you also mentioned, right? We can include a fix for that in the next release I guess

**Comment by allevo** [comment]
Fixed in https://github.com/oramasearch/orama/pull/379

**Comment by micheleriva** [comment]
Oooh fantastic. I remember you were working on this one. Thanks Tommaso!

Releasing this as part of Orama v1.0.0 next week then
