### ISSUE TITLE
Stemmer error

### ISSUE THREAD

**Issue by djibe** [oramasearch/orama#393]
Hi,

using following config: `import {stemmer} from 'https://cdn.jsdelivr.net/npm/@orama/stemmers@1.0.1/dist/fr.js';`

and then

```
language: 'french',
    components: {
      tokenizer: {
        stemming: true,
        stemmer
      }
    }
```

throws following error: `Error: Do not pass the language option to create when using a custom tokenizer.`
```

Disabling 'french' also throws an error.

Thanks.

**Comment by Rickyc81** [comment]
Are you sure? its working for me without language, it normal that it will give you an error if you pass the lenguage too.. 

``` javascript
import { stemmer } from './stemmer.js';
import { create } from '@orama/orama';
//import { stemmer } from '@orama/stemmers/italian';

const db = create({
  schema: {
    author: 'string',
    quote: 'string',
  },
  components: {
    tokenizer: {
      stemming: true,
      stemmer,
    },
  },
});
```

**Comment by djibe** [comment]
Thanks for your answer.
Cannot find stemmer.js in <https://cdn.jsdelivr.net/npm/@orama/stemmers@1.0.1/>

**Comment by Rickyc81** [comment]
> Thanks for your answer.
> 
> Cannot find stemmer.js in <https://cdn.jsdelivr.net/npm/@orama/stemmers@1.0.1/>

stemmer.js is only the content of file copied locally from cdn, only for test, but you can install it using npm as written in the documentation :)

**Comment by djibe** [comment]
Hi, `import {stemmer} from 'https://cdn.jsdelivr.net/npm/@orama/stemmers/dist/fr.js';` + above config does the thing.

Thanks
