### ISSUE TITLE
Feedback for “Create a new Orama instance”

### ISSUE THREAD

**Issue by reubenfirmin** [oramasearch/orama#395]
Can you give us more information on this page about efficient schema design? E.g.:

* What design decisions affect performance?
* Are wide tables a bad idea?
* Are deeply nested objects a bad idea?
* Would it be better keeping any columns that need to be searched on the primary object rather than nesting?
* Are you better offloading metadata that won't be searched into another storage mechanism (e.g. indexeddb / localstorage / ...)?
* Are large documents slower to "retrieve" than smaller documents, or is the only thing being returned pointers to in memory objects anyway?
* Do array fields carry search performance penalties?

**Comment by micheleriva** [comment]
Hi @reubenfirmin,
thank you so much, that's fantastic feedback!

We'll dedicate some time to clarify all the points you mentioned. Thanks again!

**Comment by jessekrubin** [comment]
also, why is everything async? 
and why do some words like `the` and `and` seem to not be searchable?
