### ISSUE TITLE
Orama Nextra | Plugin | NextRouter was not mounted

### ISSUE THREAD

**Issue by scasolari** [oramasearch/orama#396]
### Description

After using the installation guide, https://docs.oramasearch.com/plugins/plugin-nextra, and followed all the instruction I receive this error:

```
Server Error
Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted
This error happened while generating the page. Any console logs will be displayed in the terminal window.
```
### Step to reproduce

1. Add the import and component in `theme.config.jsx`
2. save and run `yarn dev`
3. open localhost:3000
4. see the error

### Expected behavior
Expected is the right working as the same search (flexsearch) as default

### Screenshots
![NextRouter was not mounted](https://snipboard.io/rz2eob.jpg)

**Desktop (please complete the following information):**
 - OS: macOS Ventura Versione 13.0 (22A380)
 - Browser: Chrome (Versione 113.0.5672.126 (Build ufficiale) (arm64))

**Comment by rjackson** [comment]
Cannot reproduce this using Nextra's default template: https://github.com/shuding/nextra-docs-template

With the changes:

```diffdiff --git a/package.json b/package.json
index 0a47d27..0edcf5e 100644
--- a/package.json
+++ b/package.json
@@ -18,6 +18,8 @@
   },
   "homepage": "https://github.com/shuding/nextra-docs-template#readme",
   "dependencies": {
+    "@orama/orama": "^1.0.8",
+    "@orama/plugin-nextra": "^1.0.8",
     "next": "^13.0.6",
     "nextra": "latest",
     "nextra-theme-docs": "latest",
diff --git a/theme.config.tsx b/theme.config.tsx
index 88b8e2b..2c95162 100644
--- a/theme.config.tsx
+++ b/theme.config.tsx
@@ -1,5 +1,6 @@
 import React from 'react'
 import { DocsThemeConfig } from 'nextra-theme-docs'
+import { OramaSearch } from '@orama/plugin-nextra'
 
 const config: DocsThemeConfig = {
   logo: <span>My Project</span>,
@@ -13,6 +14,9 @@ const config: DocsThemeConfig = {
   footer: {
     text: 'Nextra Docs Template',
   },
+  search: {
+    component: (props) => OramaSearch({...props, limitResults: 30, boost: {title: 2, description: 1, content: 1} }),
+  },
 }
 
 export default config
```

Are you able to share an example project that reproduces this issue?

**Comment by micheleriva** [comment]
Hey @scasolari, such a long time since we last spoke! 🙂

We might have a fix for this via https://github.com/oramasearch/orama/pull/429, I'll release this early next week and I'll kindly ask you to see if it solves the issue as expected. Thanks for opening the issue!
