### ISSUE TITLE
Orama Astro | Plugin | Unable to build on Windows

### ISSUE THREAD

**Issue by TheZalRevolt** [oramasearch/orama#405]
**Describe the bug**
When the build command is executed on Windows the build fail due to an error on the destination path of the index.html file.

**To Reproduce**
1. Create a new Astro Project
2. Install @orama/plugin-astro
3. Setup the plugin
4. Run astro build

**Expected behavior**
The build to complete

**Screenshots**
![build error](https://github.com/oramasearch/orama/assets/129967922/77d3d312-d1f8-4d22-bb99-15d4fbc17ce0)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: @orama/plugin-astro@1.0.2

![version](https://github.com/oramasearch/orama/assets/129967922/86e84202-220a-4294-92a1-4901b17e342f)

**Comment by micheleriva** [comment]
@Balastrong any idea? 👀

**Comment by micheleriva** [comment]
Fixed in #406
