### ISSUE TITLE
Unable to search for special characters like "++" for "c++"

### ISSUE THREAD

**Issue by codewithbugs01** [oramasearch/orama#409]
**Describe the bug**
Unable to search for special characters like "++"

**To Reproduce**
1. Set search team to '++.'
2. "No results found"

**Expected behavior**
Documents with "c++" should appear as hits.

**Comment by micheleriva** [comment]
This is due to the default of the tokenization rules. As for now, you can create a custom tokenizer with custom token-splitting rules to handle these specific cases: https://docs.oramasearch.com/internals/components#tokenizer

**Comment by codewithbugs01** [comment]
I have no idea how to do that, but I will give it a shot. 👍

**Comment by micheleriva** [comment]
@allevo maybe it's worth it to have a customizable dictionary of exceptions to be preserved during tokenization. 

Let's offline this and discuss early next week
