### ISSUE TITLE
Option to select which version to index in Docusaurus plugin

### ISSUE THREAD

**Issue by mcollina** [oramasearch/orama#413]
Currently the docusaurus plugin only index one version. It would be great to have an option to select which version we would like to index.

**Comment by micheleriva** [comment]
I guess it would be fairly simple to create different indexes for different versions, store them as static assets in the public folder, and lazy load them on request. @ShogunPanda wdyt? Could you proceed with that?

**Comment by mcollina** [comment]
It works once you select a version from the drop-down or open the docs. It does not work like that for all the pages outside of the documentation.

The problem is that in https://github.com/oramasearch/orama/blob/48005e4ae9994518597adb063ae9fc608f34d977/packages/plugin-docusaurus/src/client/theme/SearchBar/index.tsx#L88, the first element is selected.
However, that is usually the canary/next/future release. Take a look at https://docusaurus.io/.

**Comment by ShogunPanda** [comment]
This has been fixed by #416. If you feel something is still missing, feel free to reopen.
