### ISSUE TITLE
Difficulty doing primary + secondary search with `sortBy`

### ISSUE THREAD

**Issue by benmccann** [oramasearch/orama#422]
**Describe the bug**
I've added a `priority` field to my documents. The idea is that anything with a lower priority should rank lower. If the priority is the same, then it should be ranked by score. I.e. I want to rank by score but want to ensure certain pages like the migration guide and glossary always show up towards the end.

This doesn't seem to be working because the first couple results have priority 3, followed by one with priority 2, and then some again with priority 3.

I'm not sure if this is a bug or if I'm doing something wrong.

As a side note, even better than getting `sortBy` to work would be a new feature with some kind of document-based boosting. This could be either at insertion time or at query-time. I don't necessarily always want things like the glossary to show up last as much as I really want to just downrank them a bit.

**To Reproduce**
Here's a stackblitz: https://stackblitz.com/edit/stackblitz-starters-ekme6r?file=index.js

Do `pnpm install` to install dependencies and then `node . ssr` to search for the string "SSR"

It should contain:
```
    sortBy: (a, b) => {
      if (a.priority !== b.priority) {
        return b[2].priority - a[2].priority;
      }
      return b[1] - a[1];
    },
```

**Expected behavior**
All the documents with `priority` 3 should show up above those with `priority` 2. Documents with equal priority should be sorted by how well they match the search term

**Additional context**
I'm prototyping using Orama for kit.svelte.dev and svelte.dev: https://github.com/sveltejs/kit/issues/8712

**Comment by allevo** [comment]
Hi!
thanks for your report and the example is really appreciated.

I started with your example and change it a little bit to let it works correctly: https://stackblitz.com/edit/stackblitz-starters-41nxkv?file=index.js
You can find some information on our [docs](https://docs.oramasearch.com/usage/search/sorting#custom-sort), 

If you think the documentation needs to be clarified, let me know how to improve it or start a PR!

**Comment by micheleriva** [comment]
Hi @benmccann,
Is there anything else missing? Can we close the issue?

**Comment by benmccann** [comment]
Thank you! Yes, the last example is what I was looking for.

Here's a StackBlitz with just that: https://stackblitz.com/edit/stackblitz-starters-8wuzli?file=index.js

And a copy of the code for posterity here:
<details>
```
import { create, insertMultiple, search } from '@orama/orama';
import { readFileSync } from 'fs';
const query = process.argv[2];

async function run_search() {
  const blocks = JSON.parse(readFileSync('content.json'));
  blocks.forEach((b) => {
    if (b.breadcrumbs && b.breadcrumbs.length >= 1 && b.breadcrumbs[0]) {
      b.h1 = b.breadcrumbs[0];
    }
    if (b.breadcrumbs && b.breadcrumbs.length >= 2 && b.breadcrumbs[1]) {
      b.h2 = b.breadcrumbs[1];
    }
    if (b.breadcrumbs && b.breadcrumbs.length >= 3 && b.breadcrumbs[2]) {
      b.h3 = b.breadcrumbs[2];
    }
    delete b.breadcrumbs;

    if (b.href.startsWith('/docs/migrating')) {
      b.priority = 1;
    } else if (
      b.href.startsWith('/docs/types') ||
      b.href.startsWith('/docs/modules') ||
      b.href.startsWith('/docs/glossary')
    ) {
      b.priority = 2;
    } else {
      b.priority = 3;
    }
  });

  const index = await create({
    schema: {
      content: 'string',
      h1: 'string',
      h2: 'string',
      h3: 'string',
      priority: 'number',
    },
    components: {
      tokenizer: { language: 'english', stemming: true },
    },
  });

  await insertMultiple(index, blocks);

  const results = await search(index, {
    term: query,
    sortBy: (a, b) => {
      const [_docIdA, scoreA, docA] = a;
      const [_docIdB, scoreB, docB] = b;
      return docB.priority * 1000 + scoreB - (docA.priority * 1000 + scoreA);
    },
    boost: {
      h1: 4,
      h2: 3,
      h3: 2,
    },
    limit: blocks.length,
  });

  console.log(results.hits.map(({ document }) => document));
}

run_search();
```
</details>

We've got a PR open to change over to Orama in our `site-kit` repo, which is the common library used across our sites: https://github.com/sveltejs/site-kit/pull/162. I'll go ahead and get these improvements integrated there

Thank you so much for the help!

**Comment by benmccann** [comment]
We've got a PR open to change over to Orama in our `site-kit` repo, which is the common library used across our sites: https://github.com/sveltejs/site-kit/pull/162. I'll go ahead and get these improvements integrated there

Thank you so much for the help!
