### ISSUE TITLE
Is insertMultiple taking an excessively long time, or am I making a mistake?

### ISSUE THREAD

**Issue by givik** [oramasearch/orama#424]
I want to insert data to docs using **Batch insertion with insertMultiple** from the documentation. It is laggy and takes forever. What is the issue here? How does it work? Please help

**To Reproduce**
1. Go to https://codesandbox.io/s/stoic-tamas-wsqwl3?file=/index.html
2. See the source code

**Expected behavior**
Working functionality

**Desktop (please complete the following information):**
 - OS: MAC OS
 - Browser Chrome

**Comment by allevo** [comment]
Hi!
You can turn off the sort depending on what you need to speed up the insertions. I changed your example (thanks a lot for providing it!) in this one https://codesandbox.io/s/small-morning-ttvdpf?file=/index.html:1115-1148 

You can check out the documentation [here](https://docs.oramasearch.com/usage/search/sorting#disable-sort)
NB: there's a typo in the docs, I'm fixing it right now.

**Comment by givik** [comment]
@allevo you are awesome. give me time to review it. thanks

**Comment by givik** [comment]
So how to achieve performance? is this movies.json file large enough for **Orama** search? Does Orama docs have working examples where I can find the best practise for performant search? thanks

**Comment by allevo** [comment]
Hi!
No, the dataset is not "too" large for Orama.

Orama indexes all properties defined in the schema.
So the schema is used to understand which properties the search will be made on. That means during the insertion, Orama uses _all_ the fields described in the schema to understand which properties should be inserted in the indexes. Orama, by default, considers all the fields also for sorting.

For instance, in the example you posted, the property `poster` contains an URL (if I understood correctly). 
Depending on the desiderata, the final user would like to search and sort by URL or not. If not, I suggest removing it from the schema. Removing or adding a property to the schema reduces or increases respectively the time used to insert documents.

**NB**: the document inserted in the database can contain more properties than the schema ones. Obviously, the unlisted properties will be not used during the search and sorting by Orama.
**NB2**: If a property is used for the search but not for the sorting, you can read this [doc](https://docs.oramasearch.com/usage/search/sorting#memory-optimization) to remove it from the sorting only enhancing the insertion time.

**Comment by thaoula** [comment]
Hi @allevo,

I too had to disable sorting while ingesting 35k documents with about 35 fields each .. 4 of them are number fields.

When sorting was turned on I hit 100% cpu usage at 12k records and the process totally locked the container at about 16k. Turning off sorting, as suggested above, ingested the documents in about 5 minutes.

Questions

1. General question, are number fields sortable?
2. Have you guys considered an option to provide the opposite of unsortableProperties. i.e disable sorting for all fields and specify the fields to sort. This will allow making just a handful of fields sortable to utilise in this case.

Regards,
Tarek

**Comment by givik** [comment]
> Hi!
> 
> No, the dataset is not "too" large for Orama.
> 
> 
> 
> Orama indexes all properties defined in the schema.
> 
> So the schema is used to understand which properties the search will be made on. That means during the insertion, Orama uses _all_ the fields described in the schema to understand which properties should be inserted in the indexes. Orama, by default, considers all the fields also for sorting.
> 
> 
> 
> For instance, in the example you posted, the property `poster` contains an URL (if I understood correctly). 
> 
> Depending on the desiderata, the final user would like to search and sort by URL or not. If not, I suggest removing it from the schema. Removing or adding a property to the schema reduces or increases respectively the time used to insert documents.
> 
> 
> 
> **NB**: the document inserted in the database can contain more properties than the schema ones. Obviously, the unlisted properties will be not used during the search and sorting by Orama.
> 
> **NB2**: If a property is used for the search but not for the sorting, you can read this [doc](https://docs.oramasearch.com/usage/search/sorting#memory-optimization) to remove it from the sorting only enhancing the insertion time.
> 
> 

thanks for detailed explanation

**Comment by allevo** [comment]
Hi, @thaoula!
We are looking for suggestions like yours: your comment is welcome and lets us know where to improve our product!

For now, the sortable fields are `boolean`s, `string`s, and `number`s as described [here in the docs](https://docs.oramasearch.com/usage/search/sorting).

Regarding the proposal, can you open a dedicated issue asking for this feature? Also, it would be great if you want to start the implementation!

**Comment by allevo** [comment]
Closing this issue. If you need more information, feel free to reopen it or create a new issue.
