### ISSUE TITLE
Disable sort by default

### ISSUE THREAD

**Issue by allevo** [oramasearch/orama#427]
**Is your feature request related to a problem? Please describe.**
Sorting is a great feature. Anyway, it impacts the insertion performance and memory usage.
And, commonly, not used even if enabled by default.

**Describe the solution you'd like**
Disable sorting by default.

**Describe alternatives you've considered**
Enable sorting, but no properties are used for the index. Explicit on which properties the sorting is enabled. Something like
```js
const db = await create({
  schema: {
    name: 'string',
    year: 'number'
  },
  sort: {
    properties: ['year']
  }
})
await search(db, {
  term: 'tom',
  sort: {
    property: 'year'
  }
})
```
Throw an error if the specified property is not list in the scheme.

**Additional context**
-

**Comment by H4ad** [comment]
I think https://github.com/oramasearch/orama/pull/434 fix this issue.
