### ISSUE TITLE
SyntaxError: Named export 'useRouter' not found.

### ISSUE THREAD

**Issue by IlirEdis** [oramasearch/orama#439]
**Describe the bug**

I managed to implement Nextra on my existing Nextjs project also get the content remotely from a CMS (Strapi) based on this example: https://github.com/shuding/nextra/tree/main/examples/swr-site/pages/remote

However the default Nextra search functionality is not working so i came across Orama. 
After implementing it based on these instructions: https://docs.oramasearch.com/plugins/plugin-nextra

i get this error on my page:

```
SyntaxError: Named export 'useRouter' not found. The requested module 'next/router.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'next/router.js';
const { useRouter } = pkg;
```

and this typescript error in vscode: 
 
<img width="853" alt="Screenshot 2023-07-07 at 14 26 24" src="https://github.com/oramasearch/orama/assets/128377763/87b23e67-ccb2-46e4-9c12-4a578a0b4203">

also when i install it i get these warnings in terminal: 

<img width="659" alt="Screenshot 2023-07-07 at 14 50 47" src="https://github.com/oramasearch/orama/assets/128377763/3e34e5aa-1681-4a54-b079-4cb389f43b7b">

Here's also a codesandbox with my implementation of Nextra so you have an idea what im trying to explain: [codesandbox](https://codesandbox.io/p/github/IlirEdis/docs-test/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljrlzwwi000b3b6lr6x5kwu3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljrlzwwi000d3b6lvyx315vf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B38.69239677879823%252C61.30760322120177%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cljrlzwwi000b3b6lr6x5kwu3%2522%253A%257B%2522id%2522%253A%2522cljrlzwwi000b3b6lr6x5kwu3%2522%252C%2522activeTabId%2522%253A%2522cljskvxk4005g3b6l1n5c7ycr%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpages%252Fdocs%252F_meta.js%2522%252C%2522id%2522%253A%2522cljrm4vg100733b6ldle4qsnw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpages%252Fdocs%252F%255B%255B...addDocsSlug%255D%255D.mdx%2522%252C%2522id%2522%253A%2522cljrqnti001ci3b6l8sdszfbp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522cljskvxk4005g3b6l1n5c7ycr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cljrlzwwi000d3b6lvyx315vf%2522%253A%257B%2522id%2522%253A%2522cljrlzwwi000d3b6lvyx315vf%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cljrm08wk00c03b6lgdze2ze0%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cljrm0dlb00g93b6lfwf9mtf9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fdocs%252Farticle-1%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cljrm0dlb00g93b6lfwf9mtf9%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Is Orama going to work with my type of implementation?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Ali7040** [comment]
I want to work on it please assign it to me.

**Comment by micheleriva** [comment]
Done, thanks @Ali7040

**Comment by Ali7040** [comment]
@micheleriva  I am facing an issue can you please guide me on how to set it up in local env.

**Comment by Ali7040** [comment]
![image](https://github.com/oramasearch/orama/assets/81979505/f1a3209b-fd3b-41ad-847d-46403a6a66c3)
how can install node module .

**Comment by micheleriva** [comment]
you should use `pnpm`. Install it and run `pnpm install`: https://pnpm.io/installation

**Comment by Ali7040** [comment]
okay.

**Comment by Ali7040** [comment]
![image](https://github.com/oramasearch/orama/assets/81979505/14c46390-c4a7-4e63-ae28-16f156d4f015)
??

**Comment by Ali7040** [comment]
and how can i run it on local env?

**Comment by Ali7040** [comment]
@IlirEdis I think you are using `import { useRouter } from 'next/router'` in your project.
To solve this problem you should need to change the import statement.
You can use : `import { default as pkg } from 'next/router'`
`const useRouter = pkg.useRouter`
I hope this will work
