### ISSUE TITLE
searchWithHighlight crashes after persistence restore

### ISSUE THREAD

**Issue by nekdolan** [oramasearch/orama#446]
**Describe the bug**
When db is restored using data persistence plugin the search with higlight functionality no longer works

**To Reproduce**

- Add presistence plugin
- Add match highlight plugin
- Insert documents
- call persist
- call restore
- call searchWithHighlight

**Expected behavior**
not crash with error

**Screenshots**
```
const db = await create({
        schema: {
            // id: 'string',
            text: 'string',
            name: 'string',
            type: 'string',
            year: 'number',
            source: 'string',
            author: 'string'
        },
        components: {
            // Register the hook
            afterInsert: [highlightAfterInsert],
            tokenizer: {
                stopWords: englishStopwords,
                stemming: true,
                stemmer
            },
        }
    })
```
```
TypeError: Cannot read properties of undefined (reading '21650872-55')          1:49:20 PM
    at file:///Users/trinimac/WebstormProjects/lazarites/node_modules/@orama/plugin-match-highlight/dist/index.js:52:78
    at Array.map (<anonymous>)
    at searchWithHighlight (file:///Users/trinimac/WebstormProjects/lazarites/node_modules/@orama/plugin-match-highlight/dist/index.js:51:30)
    at async cachedEventHandler.swr (file:///Users/trinimac/WebstormProjects/lazarites/.nuxt/dev/index.mjs:5363:21)
    at async file:///Users/trinimac/WebstormProjects/lazarites/.nuxt/dev/index.mjs:1584:20
    at async _resolve (file:///Users/trinimac/WebstormProjects/lazarites/.nuxt/dev/index.mjs:1445:23)

```

**Desktop (please complete the following information):**
 - NodeJS Nuxt 3 server

**Comment by allevo** [comment]
Hi, thank you for opening this issue!
Which version of Orama are you using for dumping and searching?
Which version of Orama persistence & highlight plugins are you using?
I suggest you to use the same version everywhere

**Comment by micheleriva** [comment]
Hi @nekdolan any update on the above questions from @allevo above?

**Comment by benjaminleonard** [comment]
I am seeing this too, not with Orama persistence but I have my own code for retrieving it from json.

```
"@orama/plugin-match-highlight": "^1.2.1",
"@orama/orama": "^1.2.1",
```

**Comment by benjaminleonard** [comment]
I believe the issue might be in the `save()` function. If I don't use that I can see `"positions"` in the output, but it's not in what is returned from `save()`

**Comment by benjaminleonard** [comment]
Perhaps something like this within `@orama/plugin-match-highlight`:

```ts
export type RawDataWithPositions = RawData & {
  positions: Position[]
}

export async function saveWithHighlight(orama: Orama): Promise<RawDataWithPositions> {
  const data = save(orama)

  return {
    ...data,
    positions: orama.positions
  }
}
```

**Comment by benjaminleonard** [comment]
I think I have it working, but there seems to be an issue in the `load()` function. It's not adding the `positions` object.  My example works with:

```ts
await load(db, dbData)
db.data.positions = dbData.positions
```
