### ISSUE TITLE
support sanskrit diacriticals

### ISSUE THREAD

**Issue by sujato** [oramasearch/orama#465]
**Is your feature request related to a problem? Please describe.**

My app uses Buddhist texts with Pali and Sanskrit but they're not supported in orama.

**Describe the solution you'd like**

Support common uses for Pali and Sanskrit.

Here are the usual substitutions:

```
ā = a
ī = i
ū = u
ṛ = r
ḷ = l
ṃ = m
ṁ = m
ḥ = h
ś = sh
ṣ = sh
ṭ = t
ḍ = d
ṇ = n
ṅ = n
ñ = n or ny or gn
ḻ = l
ḹ = l
ṝ = r
```

And the respective charcodes, including uppercase. I think!

```
240
241
256
257
298
299
346
347
362
363
7692
7693
7716
7717
7734
7735
7736
7737
7738
7739
7744
7745
7746
7747
7748
7749
7750
7751
7770
7771
7772
7773
7778
7779
7788
7789
```

**Comment by utsav00** [comment]
I'd like to take a stab at this.
/attempt #465

**Comment by rishi-raj-jain** [comment]
@micheleriva 

Can you help me where these subsitutions are done?
