### ISSUE TITLE
Changes too important in version 1.2.5

### ISSUE THREAD

**Issue by philippebeaulieu** [oramasearch/orama#488]
I’m working to integrate the latest changes from Orama 1.2.5. The new types are hard to figure out. I’m having difficulties that are over what a micro release should include.

I looked and the documentation hasn’t been updated to reflect these new types.

Wouldn’t it be better to bump it to 1.3 ? That would leave version 1.2.x with the previous types and make transition easier.

Some of the choices are not easy to understand at a glance. Like the type requested by the create() method. I get this error when I try to use a generic that extends AnyOrama (something I tried that seemed to be the replacement for the previous Document type).

Argument of type 'Document' is not assignable to parameter of type PartialSchemaDeep<Schema<Schema<Document>>>

**Comment by micheleriva** [comment]
Hi @philippebeaulieu, thanks for this feedback.

I think we will need to discuss internally how to manage this (cc. @H4ad, @allevo). We'll get back to you asap.

**Comment by micheleriva** [comment]
@philippebeaulieu any update on this? Or else I need to close this due to inactivity
