### ISSUE TITLE
Normalization cache overriden when creating orama instance

### ISSUE THREAD

**Issue by armandoroman1016** [oramasearch/orama#492]
**Describe the bug**

When creating an orama instance, I am using the tokenizer config property to provide a normalization cache with preset values but doesn't end up being used and defaults to an empty cache. 

Unless it is intentionally ignored, the fix for this seems straightforward. ([updating this LOC](https://github.com/oramasearch/orama/blob/main/packages/orama/src/components/tokenizer/index.ts#L145)). 

**To Reproduce**

Here's a codesandbox with reproducible code. https://codesandbox.io/p/sandbox/competent-cookies-4qmwh7?file=%2Fsrc%2Findex.ts%3A15%2C64

```typescript
import { create } from "@orama/orama";

(async () => {
  const orama = await create({
    schema: {
      foo: "string",
    },
    components: {
      tokenizer: {
        normalizationCache: new Map([["english:foo:Bar", "bar"]]),
        stemming: true,
      },
    },
  });
  console.log(orama.tokenizer.normalizationCache); // Empty map
})();

```
**Expected behavior**

Based on [documentation](https://docs.oramasearch.com/internals/components#tokenizer) regarding tokenizer configuration I would expect the provided map to be used when initializing a DB.

**Screenshots**

n/a

**Desktop (please complete the following information):**
 - OS: `macOS 13.5.2`
 - Node version - 18.17.1
 - Browser - n/a - search done server side
 - Version - n/a - search done server side

**Smartphone (please complete the following information):**

n/a

**Additional context**

**Comment by micheleriva** [comment]
Hi @armandoroman1016 ! Thanks for opening this. I'm only asking since you've already identified a potential solution: would you be able to open a PR for that?

**Comment by micheleriva** [comment]
@stearm feel free to go ahead if you have a solution in mind
