### ISSUE TITLE
searchResultWithHighlight incorrectly typed

### ISSUE THREAD

**Issue by tpict** [oramasearch/orama#496]
**Describe the bug**
[See guide on setting up highlighting](https://docs.oramasearch.com/plugins/plugin-match-highlight). It indicates that the results will come in shape
```js
{
  elapsed: {...},
  count: ...,
  hits: [
    {
      id: ...,
      score: ...,
      document: { text: 'hello world' },
      positions: {
        text: {
          hello: [
            {
              start: 0,
              length: 5
            }
          ]
        }
      }
    }
  ]
}
```

but if you do `typeof results.hits[number].positions[number]`, you get `Position` which is just the innermost object with `{ start: number; length: number; }`. This doesn't line up with the record of document fields -> search hits -> positions seen in the example.

**To Reproduce**
Follow example above

**Expected behavior**
`hits.positions` is correctly typed

**Screenshots**
<img width="584" alt="image" src="https://github.com/oramasearch/orama/assets/12588098/bb0a67c8-f851-4ee3-af41-be07c3f792ed">

**Desktop (please complete the following information):**
 - OS: macOS 12
 - Browser: N/A
 - Version: `"@orama/orama": "^1.2.8"`, `"@orama/plugin-match-highlight": "^1.2.8",`

**Comment by micheleriva** [comment]
Hi @tpict! Thanks for opening this.
I'll put a $50 bounty to anyone willing to fix this.

/bounty 50
