### ISSUE TITLE
Can't build react/typescript project

### ISSUE THREAD

**Issue by govorov** [oramasearch/orama#499]
Good evening dear team,

After a fresh install in an existing react/typescript project and trying to `import { create } from "@orama/orama";`  the build keeps failing with multiple errors like below:

```
TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@orama/orama")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to '/home/stas/dev/ijsvogel/client_web/package.json'.
```
 
Following the instructions given in the error message doesn't help, module resolution remains broken.

typescript version is 4.9.5

Any ideas where to look at?
Thank you.

**Comment by micheleriva** [comment]
Hi @govorov, looks like you're using Orama in a CommonJS project. You can follow the instructions here: https://docs.oramasearch.com/plugins/plugin-data-persistence#typescript

**Comment by gabrielsantosblanchet** [comment]
> Hi @govorov, looks like you're using Orama in a CommonJS project. You can follow the instructions here: https://docs.oramasearch.com/plugins/plugin-data-persistence#typescript

this links point to a 404 can I have the new relevent documentation for this case ?

**Comment by raiindev** [comment]
@gabrielsantosblanchet Here you go https://docs.askorama.ai/open-source/plugins/plugin-data-persistence#typescript

**Comment by gabrielsantosblanchet** [comment]
> @gabrielsantosblanchet Here you go https://docs.askorama.ai/open-source/plugins/plugin-data-persistence#typescript

weird I'm still having the issue, but how do I import these without being as type, and without converting my whole project into esm. I'm following the documentation and it is not working
