### ISSUE TITLE
"Class extends value undefined..." when using restore from plugin-data-persistence

### ISSUE THREAD

**Issue by ghostdevv** [oramasearch/orama#500]
**Describe the bug**

When using `@orama/plugin-data-persistence` I get the following error:

```
TypeError: Class extends value undefined is not a constructor or null
    at ../../node_modules/.pnpm/dpack@0.6.22/node_modules/dpack/lib/serialize-stream.js (serialize-stream.js:5:1)
    at __require (chunk-ZC22LKFR.js?v=90517abf:9:50)
    at ../../node_modules/.pnpm/dpack@0.6.22/node_modules/dpack/index.js (index.js:5:33)
    at __require (chunk-ZC22LKFR.js?v=90517abf:9:50)
    at index.ts:6:24
handleError @ app.js:26
```

This issue exists #219 but is marked as a duplicate of something that no longer exists

**To Reproduce**
```ts
import searchIndex from 'searchIndex.json?raw'; // this is a string, unparsed json
const searchDb = await restore('json', searchIndex, 'browser');
```

**Expected behavior**
No Error

**Comment by micheleriva** [comment]
Hi @ghostdevv,
from the error trace, I see Orama is using `dpack` to deserialize the index, even though you're restoring it as `'json'`.

Also, `restore` does not accept a third argument, as it expects the imported db to be in-memory already.

If you're restoring from disk, you should use:

```js
import { persistToFile } from '@orama/plugin-data-persistence/server'
 
const filePath = await persistToFile(originalInstance, 'binary', './quotes.msp')
```

As per the documentation here: https://docs.oramasearch.com/plugins/plugin-data-persistence.

If you're still having the issue, could you please send a repro via CodeSandbox or Stackblitz? You can also send it on Slack at https://orama.to/slack.

Thanks!

**Comment by rikimbili** [comment]
> @micheleriva Is there a way to restore it from disk without using `node:fs`. I am using this inside SvelteKit and would like to generate the db in a script on the server and then load it and search it in the client

Were you ever able to achieve this?

**Comment by ghostdevv** [comment]
> Were you ever able to achieve this?

Nope, I also opened #522 I can't remember how far I got with that

**Comment by rikimbili** [comment]
> > Were you ever able to achieve this?
> 
> Nope, I also opened #522 I can't remember how far I got with that

Just to give you an update, I was able to work around this issue using a polyfill. The issue seems to be that vite does not provide polyfills for node native modules like stream by default (which is the issue here).

I'm no longer getting that issue when using this plugin: https://github.com/davidmyersdev/vite-plugin-node-polyfills

**Comment by JustroX** [comment]
I'm still encountering this issue. I can't seem to find the continuation of the discussion inside slack since older posts are hidden. For context, I'm running orama inside storybook.

```
TypeError: Class extends value undefined is not a constructor or null
    at ./node_modules/dpack/lib/serialize-stream.js (http://localhost:4400/vendors-node_modules_orama_plugin-data-persistence_dist_index_js-node_modules_spartan-ng_ui-a-5fd193.iframe.bundle.js:8184:36)
    at __webpack_require__ (http://localhost:4400/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:4400/runtime~main.iframe.bundle.js:338:21)
    at ./node_modules/dpack/index.js (http://localhost:4400/vendors-node_modules_orama_plugin-data-persistence_dist_index_js-node_modules_spartan-ng_ui-a-5fd193.iframe.bundle.js:6641:33)
    at __webpack_require__ (http://localhost:4400/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:4400/runtime~main.iframe.bundle.js:338:21)
    at ./node_modules/@orama/plugin-data-persistence/dist/index.js (http://localhost:4400/vendors-node_modules_orama_plugin-data-persistence_dist_index_js-node_modules_spartan-ng_ui-a-5fd193.iframe.bundle.js:6167:63)
    at __webpack_require__ (http://localhost:4400/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:4400/runtime~main.iframe.bundle.js:338:21)
    at ./libs/client/cms-mobile/orama/src/lib/orama.service.ts (http://localhost:4400/search-src-lib-search-component-stories.iframe.bundle.js:18:88)
```

```ts
import { Injectable } from '@angular/core';
import { Orama, create } from '@orama/orama';
import { restore } from '@orama/plugin-data-persistence';

@Injectable({ providedIn: 'root' })
export class OramaService {
  async mount(data: string) {
    const db = await restore('json', data); // when I comment this out, it's working
  }
}
```

**Comment by kucukkanat** [comment]
For anyone stumbling upon this only to find this issue closed before a proper solution:

I am having the same issue and I couldn't find a proper solution. 
I can't take the `vite-plugin-node-polyfills` approach because I am using `bun build` as a bundler. 
The **workaround** I found was to write my own JSON export/importer like below: 
```js
// I have a class that keeps all relevant methods and `this.store` as the database instance. Here are some methods I implemented to workaround

/**
   * Returns the persisted JSON string or buffer of the in memory database
   * @returns {Promise<Array<any>>}
   */
  async persist() {
    await this.assureInit();
    const persistedjson = Object.values(this.store.data.docs.docs);
    return persistedjson;
  }

  /**
   * Loads from a previous persisted JSON string or buffer
   * @param {any} json
   */
  async load(json) {
    await this.assureInit();
    await insertMultiple(this.store, json);
  }
```

**Comment by jacob-8** [comment]
In SvelteKit 2/Vite 5.4.2 trying to use `import { restore } from '@orama/plugin-data-persistence';` browser side still throws the same error mentioned above. Trying to do node polyfills didn't solve anything and doesn't feel like the right solution here. If you look at the [source code](https://github.dev/oramasearch/orama/tree/main/packages/plugin-data-persistence) you'll realize that for using the json format `@orama/plugin-data-persistence` is completely unneeded. Just do this:

```js
import { load, save } from '@orama/orama'
import saved_index from './saved_index.json?raw'
import { my_schema } from './my_schema'

function restore() {
  const index = create({ schema: my_schema })
  const deserialized = JSON.parse(saved_index)
  load(index, deserialized)
  return index // can now use `index` as expected
}

function persist(index) {
  const dbExport = await save(index)
  return JSON.stringify(dbExport)
}
```

Dpack seems to have nice compression benefits so it would be cool to use that instead but at least the above code gets things working.
