### ISSUE TITLE
Sample code on stemming doc does not work

### ISSUE THREAD

**Issue by corradopetrelli** [oramasearch/orama#512]
**Describe the bug**
The sample code in the [stemming documentation page](https://docs.oramasearch.com/text-analysis/stemming) does not work.

**To Reproduce**
1. Go to https://docs.oramasearch.com/text-analysis/stemming
2. Copy copy the contained code
```javascript
import { create } from '@orama/orama'
import { stemmer } from '@orama/stemmers/italian'
 
const db = create({
  schema: {
    author: 'string',
    quote: 'string',
  },
  language: 'italian',
  components: {
    tokenizer: {
      stemming: true,
      stemmer
    },
  },
})
```
3. Install `@orama/orama`
4. Install `@orama/stemmers`
5. Execute code
6. Error code: `NO_LANGUAGE_WITH_CUSTOM_TOKENIZER`

**Expected behavior**

No errors should appear

**Screenshots**

![image](https://github.com/oramasearch/orama/assets/36475130/8323c918-8b21-4690-a106-05feaa1c4207)

**Desktop:**
 - OS: macOS
 - pnpm: 8.6.1
 - node: 18

**Additional context**
/

**Comment by micheleriva** [comment]
fixed in https://github.com/oramasearch/orama/pull/513
