### ISSUE TITLE
Use plugin-data-persistence in the browser

### ISSUE THREAD

**Issue by ghostdevv** [oramasearch/orama#522]
**Is your feature request related to a problem? Please describe.**

I want to be able to generate a search database in a script which I save to a file using `persistToFile` from `@orama/plugin-data-persistence/server`, and then import that persisted database from the client (browser).

Currently I am regenerating the search index every time a user loads the page, and also again whenever SSR occurs which I don't think is ideal

**Describe the solution you'd like**

A client side compatible `restoreFromFile`

**Describe alternatives you've considered**

Using a network request when searching

**Comment by micheleriva** [comment]
Hi there! You should probably use the following function:

```js
import { search } from '@orama/orama'
import { restore } from '@orama/plugin-data-persistence'
 
const newInstance = await restore('json', JSONIndex)
 
await search(newInstance, {
  term: '...'
})
```

in that case, `JSONIndex` must be a JSON dump of the database (typically generated with the same plugin).

Full documentation here: https://docs.oramasearch.com/open-source/plugins/plugin-data-persistence
