### ISSUE TITLE
Wrong type definition for stopwords?

### ISSUE THREAD

**Issue by flodiebold** [oramasearch/orama#524]
**Describe the bug**
Are the definition files for stopwords wrong, or am I doing something wrong when importing them?

**To Reproduce**
```typescript
import { stopwords } from "@orama/stopwords/german";
```
then use `stopwords` later. This results in a `'stopwords' only refers to a type, but is being used as a value here` error.

**Expected behavior**
No type error.

**Additional context**
The definition files for the stopwords say:
```typescript
export type stopwords = string[]
```
https://github.com/oramasearch/orama/blob/060db43ac1a831c456ff855a5bc2fb073bce9999/packages/stopwords/scripts/build.js#L56

Shouldn't this be 
```typescript
export const stopwords: string[]
```
instead?

**Comment by micheleriva** [comment]
Hi @flodiebold, it looks like you're right. Would you ming maybe opening a PR for this? Thanks!
