### ISSUE TITLE
Single file distribution

### ISSUE THREAD

**Issue by bartlomieju** [oramasearch/orama#533]
I followed https://docs.oramasearch.com/ and was looking for browser imports. The suggested one is `https://unpkg.com/@orama/orama@latest/dist/index.js`.

However, after inspecting it, I see the following:
```
export { create } from './methods/create.js';
export { count, getByID } from './methods/docs.js';
export { insert, insertMultiple } from './methods/insert.js';
export { remove, removeMultiple } from './methods/remove.js';
export { search } from './methods/search.js';
export { searchVector } from './methods/search-vector.js';
export { load, save } from './methods/serialization.js';
export { update, updateMultiple } from './methods/update.js';
export * from './types.js';
export * as components from './components.js';
export * as internals from './internals.js';

//# sourceMappingURL=index.js.map
```

It imports a bunch of files which can cause a waterfall and poor loading speed in the browser. I'm trying to add Orama as a client side search engine in https://github.com/denoland/deno_doc/pull/355 and was wondering if there's a single file distribution? I'd like to include a single `<script>` tag in the generated content and have to download only a single file.

**Comment by micheleriva** [comment]
Hi @bartlomieju,
we don't currently support a single-file distribution, but I guess we could easily make it happen with the next release. I'll reach out privately to give more context

**Comment by micheleriva** [comment]
Closing as not needed after taking this offline
