### ISSUE TITLE
Slow indexing in firefox

### ISSUE THREAD

**Issue by rpiosi** [oramasearch/orama#559]
### Describe the bug

I noticed indexing is about 2.5x slower in firefox. Is it a known issue? Is firefox just this much slower or something can be done on orama side?

### To Reproduce

- Launch Firefox
- Run indexing of a large dataset

### Expected behavior

Indexing times should be about the same in all modern browsers.

### Environment Info

```bash
Ubuntu 22.04
Firefox 120
Chrome 119
```

### Affected areas

Initialization, Data Insertion

**Comment by micheleriva** [comment]
Hi @rpiosi,
Orama works best on V8 and JSC-powered runtimes, as the optimizations are well-known and easier to manage. Is the problem related to insertion only? How is the document schema structured?

**Comment by micheleriva** [comment]
Fixed in #428
