### ISSUE TITLE
Update test suite

### ISSUE THREAD

**Issue by micheleriva** [oramasearch/orama#578]
### Problem Description

Our test suite runs on Tap 16. We need to upgrade to Tap 18.

### Proposed Solution

Upgrade to Tap 18

**Comment by debiff** [comment]
I would like to participate, could I take care of this?

**Comment by micheleriva** [comment]
Yes @debiff, feel free to go ahead

**Comment by micheleriva** [comment]
So the tests occasionally pass locally, then break in CI. Looks like there's some process hanging at some point. An unique resolution would be a nice to have
