### ISSUE TITLE
Blog: All blog articles get 404 when you open them

### ISSUE THREAD

**Issue by bozzelliandrea** [oramasearch/orama#590]
### Describe the bug

The error seems the routing, when you click one article you are router to https://oramasearch.com/blog/blog/seqproto-fast-binary-serialization-in-javascript .
as you can see, the repeated path `/blog/blog` breaks the link

### To Reproduce

1. go to https://oramasearch.com/blog/
2. click on any article from the blog page
3. get 404

### Expected behavior

the page rendered 

### Environment Info

```bash
Chrome: 119.0.6045.199v
```

### Affected areas

Search

**Comment by bozzelliandrea** [comment]
Sorry for the affected areas "Search" but i couldn't find the Blog or Docs area

**Comment by allevo** [comment]
Fixed, and thanks for spotting it!
