### ISSUE TITLE
support mmkv

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [oramasearch/orama#600]
it would be really useful if this supported https://github.com/mrousavy/react-native-mmkv since mmkv it really fast and supports mobile and web

**Comment by micheleriva** [comment]
Hi @Ashraf-Ali-aa, I'm not sure what do you mean by that?

**Comment by Ashraf-Ali-aa** [comment]
@micheleriva I wanted to persist the data used by orama. react native mmkv supports storing data in mobile and web, I thought it might be a good option to combine them to have full offline search.

**Comment by micheleriva** [comment]
Have you tried using our data persistence plugin?

https://docs.oramasearch.com/open-source/plugins/plugin-data-persistence#data-persistence
