### ISSUE TITLE
CaseSensitive search

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [oramasearch/orama#61]
**Is your feature request related to a problem? Please describe.**
At the moment the search is case-insensitive, so it could be useful to add a parameter to specify if the search must be in case-sensitive

**Describe the solution you'd like**
Adding a parameter during the search called `caseSensitive` could be good enough.

**Comment by AlessandroMinoccheri** [comment]
We can add to `SearchParams`  type the new property `caseSensitive` nullable and we can pass to the function `tokenize` the param to apply, or not, the lower case.

**Comment by micheleriva** [comment]
How would this impact the search results? We're also planning to give support to `tf-idf` (or similar algorithm) to determine the weight of a given token depending on the context, would case sensitivity impact here as well?

**Comment by AlessandroMinoccheri** [comment]
I think that we can add this as a little feature, not so much effort.
And if we will add a better algorithm we can remove the feature.
I think it's not a killer feature for the tool so it's not urgent.

**Comment by micheleriva** [comment]
Closing as we're not planning this activity anytime soon
