### ISSUE TITLE
The homepage of the website is blank

### ISSUE THREAD

**Issue by Gitstar-OC** [oramasearch/orama#844]
### Describe the bug

Refer to the below video for more details

https://github.com/user-attachments/assets/547bab30-a825-4205-bf32-764b1e932fc6

### To Reproduce

Visit the website you can see the error. 

### Expected behavior

The image / video is just blank on the homepage

### Environment Info

```bash
OS: Windows (11 Latest version) 
Browser: Chrome (Up to date updated)
Location: Maharashtra, India
```

### Affected areas

Initialization

### Additional context

Every other thing is working fine, this might be due to a deployment error.

**Comment by Gitstar-OC** [comment]
It is the iframe component, I might work on this issue if I get the root cause of why this is happening. 
![image](https://github.com/user-attachments/assets/35a85b0a-6ccb-411c-8093-13040e69e800)

**Comment by Gitstar-OC** [comment]
The cdn the iframe is requesting from has nothing 
![image](https://github.com/user-attachments/assets/28dde9aa-538c-4f50-83b4-027f21dee43a)

**Comment by faustoq** [comment]
Fixed. Thanks for spotting it and reporting it to us.
